const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Network:", hre.network.name);

  // 1. Deploy MockUSDC
  console.log("\n1. Deploying MockUSDC...");
  const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("   MockUSDC:", usdcAddress);

  // 2. Deploy PredictionMarketV4 (升级版：支持 CPMM + LMSR 双算法)
  console.log("\n2. Deploying PredictionMarketV4...");
  const PredictionMarket = await hre.ethers.getContractFactory("PredictionMarketV4");
  const predictionMarket = await PredictionMarket.deploy(usdcAddress);
  await predictionMarket.waitForDeployment();
  const predictionAddress = await predictionMarket.getAddress();
  console.log("   PredictionMarketV4:", predictionAddress);

  // 3. Deploy CreatorMarketV3 (升级版：支持多曲线类型)
  console.log("\n3. Deploying CreatorMarketV3...");
  const CreatorMarket = await hre.ethers.getContractFactory("CreatorMarketV3");
  const creatorMarket = await CreatorMarket.deploy(usdcAddress);
  await creatorMarket.waitForDeployment();
  const creatorAddress = await creatorMarket.getAddress();
  console.log("   CreatorMarketV3:", creatorAddress);

  // 获取 Chain ID
  const network = await hre.ethers.provider.getNetwork();
  const chainId = Number(network.chainId);

  // 4. 保存 deployed-addresses.json
  const addresses = {
    MockUSDC: usdcAddress,
    PredictionMarketV4: predictionAddress,
    CreatorMarketV3: creatorAddress,
    deployer: deployer.address,
    network: hre.network.name,
    chainId: chainId,
    timestamp: new Date().toISOString(),
    // 新增：记录合约特性
    features: {
      predictionMarket: {
        version: 4,
        algorithms: ["CPMM", "LMSR"],
        description: "支持 CPMM 和 LMSR 双定价算法"
      },
      creatorMarket: {
        version: 3,
        curveTypes: ["LINEAR", "EXPONENTIAL", "SIGMOID"],
        description: "支持线性、指数、Sigmoid 三种联合曲线"
      }
    }
  };

  fs.writeFileSync(
    "deployed-addresses.json",
    JSON.stringify(addresses, null, 2)
  );
  console.log("\n✅ Saved deployed-addresses.json");

  // 5. 自动更新前端 config.ts
  const frontendConfigPath = path.join(__dirname, "../../frontend/src/constants/config.ts");
  
  const configContent = `// Auto-generated by deployV4.js - ${new Date().toISOString()}
// Network: ${hre.network.name} (Chain ID: ${chainId})

export const PREDICTION_MARKET_ADDRESS = "${predictionAddress}";
export const CREATOR_MARKET_ADDRESS = "${creatorAddress}";
export const USDC_ADDRESS = "${usdcAddress}";
export const CHAIN_ID = ${chainId};
export const CHAIN_NAME = "${hre.network.name}";

// USDC decimals
export const USDC_DECIMALS = 6;

// Contract versions
export const PREDICTION_MARKET_VERSION = 4;
export const CREATOR_MARKET_VERSION = 3;

// Prediction Market 算法类型
export enum PricingAlgorithm {
  CPMM = 0,   // 恒定乘积做市商
  LMSR = 1    // 对数市场评分规则
}

// Creator Market 曲线类型
export enum CurveType {
  LINEAR = 0,      // 线性曲线: price = A * supply + B
  EXPONENTIAL = 1, // 指数曲线: price = B + A * supply²
  SIGMOID = 2      // S型曲线: 早期慢 -> 中期快 -> 后期慢
}

// 默认曲线参数
export const DEFAULT_CURVE_A = 10000;        // 0.01 USDC 斜率
export const DEFAULT_CURVE_B = 1000000;      // 1 USDC 基础价格
export const DEFAULT_INFLECTION = 100;       // Sigmoid 拐点
export const DEFAULT_LMSR_B = "100000000000000000000"; // 100 * 10^18

// RPC URL (for reference)
export const RPC_URL = "${getRpcUrl(hre.network.name)}";
`;

  try {
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log("✅ Updated frontend/src/constants/config.ts");
  } catch (error) {
    console.log("⚠️ Could not update frontend config:", error.message);
  }

  // 6. 自动更新 Oracle .env
  const oracleDir = path.join(__dirname, "../../oracle-node");
  
  if (!fs.existsSync(oracleDir)) {
    fs.mkdirSync(oracleDir, { recursive: true });
  }

  const oracleEnvPath = path.join(oracleDir, ".env");
  let existingPrivateKey = "你的私钥";
  let existingRapidApiKey = "你的RapidAPI密钥";
  
  if (fs.existsSync(oracleEnvPath)) {
    const existingEnv = fs.readFileSync(oracleEnvPath, 'utf8');
    const privateKeyMatch = existingEnv.match(/PRIVATE_KEY=(.+)/);
    const rapidApiMatch = existingEnv.match(/RAPIDAPI_KEY=(.+)/);
    if (privateKeyMatch && privateKeyMatch[1] && !privateKeyMatch[1].includes('你的')) {
      existingPrivateKey = privateKeyMatch[1];
    }
    if (rapidApiMatch && rapidApiMatch[1] && !rapidApiMatch[1].includes('你的')) {
      existingRapidApiKey = rapidApiMatch[1];
    }
  }

  const envContent = `# Auto-generated by deployV4.js - ${new Date().toISOString()}
# Network: ${hre.network.name} (Chain ID: ${chainId})

RPC_URL=${getRpcUrl(hre.network.name)}
PRIVATE_KEY=${existingPrivateKey}

# Contract Addresses (V4)
PREDICTION_MARKET_ADDRESS=${predictionAddress}
CREATOR_MARKET_ADDRESS=${creatorAddress}
USDC_ADDRESS=${usdcAddress}

# Contract Versions
PREDICTION_MARKET_VERSION=4
CREATOR_MARKET_VERSION=3

RAPIDAPI_KEY=${existingRapidApiKey}
RAPIDAPI_HOST=twitter241.p.rapidapi.com

PORT=3001
`;

  try {
    fs.writeFileSync(oracleEnvPath, envContent);
    console.log("✅ Updated oracle-node/.env");
    
    fs.writeFileSync(path.join(oracleDir, ".env.example"), envContent);
    console.log("✅ Updated oracle-node/.env.example");
  } catch (error) {
    console.log("⚠️ Could not update oracle .env:", error.message);
  }

  // 打印总结
  console.log("\n" + "=".repeat(60));
  console.log("🎉 ALL CONTRACTS DEPLOYED SUCCESSFULLY!");
  console.log("=".repeat(60));
  console.log("\n📋 Contract Addresses:");
  console.log("   MockUSDC:            ", usdcAddress);
  console.log("   PredictionMarketV4:  ", predictionAddress);
  console.log("   CreatorMarketV3:     ", creatorAddress);
  console.log("\n🌐 Network Info:");
  console.log("   Network:  ", hre.network.name);
  console.log("   Chain ID: ", chainId);
  console.log("   Deployer: ", deployer.address);
  console.log("\n🆕 New Features in V4:");
  console.log("   📊 PredictionMarket: CPMM + LMSR 双定价算法");
  console.log("   📈 CreatorMarket: Linear/Exponential/Sigmoid 多曲线");
  console.log("=".repeat(60));

  // 7. 验证提示
  console.log("\n📝 Next Steps:");
  console.log("   1. 更新前端 hooks 以支持新的合约 ABI");
  console.log("   2. 如果在测试网，可以运行验证脚本:");
  console.log(`      npx hardhat verify --network ${hre.network.name} ${predictionAddress} ${usdcAddress}`);
  console.log(`      npx hardhat verify --network ${hre.network.name} ${creatorAddress} ${usdcAddress}`);
  console.log("   3. 测试新功能:");
  console.log("      - 创建 LMSR 算法的预测市场");
  console.log("      - 创建使用指数/Sigmoid 曲线的创作者");
}

function getRpcUrl(networkName) {
  const rpcUrls = {
    sepolia: "https://eth-sepolia.g.alchemy.com/v2/BVg93ArKlmUQFHzHqureN",
    baseSepolia: "https://sepolia.base.org",
    base: "https://mainnet.base.org",
    mainnet: "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY",
    localhost: "http://127.0.0.1:8545"
  };
  return rpcUrls[networkName] || "https://sepolia.base.org";
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});