const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Network:", hre.network.name);

  // 1. Deploy MockUSDC
  console.log("\n1. Deploying MockUSDC...");
  const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("   MockUSDC:", usdcAddress);

  // 2. Deploy PredictionMarketV3
  console.log("\n2. Deploying PredictionMarketV3...");
  const PredictionMarket = await hre.ethers.getContractFactory("PredictionMarketV3");
  const predictionMarket = await PredictionMarket.deploy(usdcAddress);
  await predictionMarket.waitForDeployment();
  const predictionAddress = await predictionMarket.getAddress();
  console.log("   PredictionMarketV3:", predictionAddress);

  // 3. Deploy CreatorMarketV2
  console.log("\n3. Deploying CreatorMarketV2...");
  const CreatorMarket = await hre.ethers.getContractFactory("CreatorMarketV2");
  const creatorMarket = await CreatorMarket.deploy(usdcAddress);
  await creatorMarket.waitForDeployment();
  const creatorAddress = await creatorMarket.getAddress();
  console.log("   CreatorMarketV2:", creatorAddress);

  // 获取 Chain ID
  const network = await hre.ethers.provider.getNetwork();
  const chainId = Number(network.chainId);

  // 4. 保存 deployed-addresses.json
  const addresses = {
    MockUSDC: usdcAddress,
    PredictionMarketV3: predictionAddress,
    CreatorMarketV2: creatorAddress,
    deployer: deployer.address,
    network: hre.network.name,
    chainId: chainId,
    timestamp: new Date().toISOString()
  };

  fs.writeFileSync(
    "deployed-addresses.json",
    JSON.stringify(addresses, null, 2)
  );
  console.log("\n✅ Saved deployed-addresses.json");

  // 5. 自动更新前端 config.ts
  const frontendConfigPath = path.join(__dirname, "../../frontend/src/constants/config.ts");
  
  const configContent = `// Auto-generated by deployV3.js - ${new Date().toISOString()}
// Network: ${hre.network.name} (Chain ID: ${chainId})

export const PREDICTION_MARKET_ADDRESS = "${predictionAddress}";
export const CREATOR_MARKET_ADDRESS = "${creatorAddress}";
export const USDC_ADDRESS = "${usdcAddress}";
export const CHAIN_ID = ${chainId};
export const CHAIN_NAME = "${hre.network.name}";

// USDC decimals
export const USDC_DECIMALS = 6;

// Contract version
export const PREDICTION_MARKET_VERSION = 3;

// RPC URL (for reference)
export const RPC_URL = "${getRpcUrl(hre.network.name)}";
`;

  try {
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log("✅ Updated frontend/src/constants/config.ts");
  } catch (error) {
    console.log("⚠️ Could not update frontend config:", error.message);
  }

  // 找到这段代码，替换成下面的版本：

  // ============ 6. 自动更新 Oracle .env ============
  const oracleDir = path.join(__dirname, "../../oracle-node");
  
  // 确保目录存在
  if (!fs.existsSync(oracleDir)) {
    fs.mkdirSync(oracleDir, { recursive: true });
  }

  // 读取现有的 .env 文件（如果存在），保留敏感信息
  const oracleEnvPath = path.join(oracleDir, ".env");
  let existingPrivateKey = "你的私钥";
  let existingRapidApiKey = "你的RapidAPI密钥";
  
  if (fs.existsSync(oracleEnvPath)) {
    const existingEnv = fs.readFileSync(oracleEnvPath, 'utf8');
    const privateKeyMatch = existingEnv.match(/PRIVATE_KEY=(.+)/);
    const rapidApiMatch = existingEnv.match(/RAPIDAPI_KEY=(.+)/);
    if (privateKeyMatch && privateKeyMatch[1] && !privateKeyMatch[1].includes('你的')) {
      existingPrivateKey = privateKeyMatch[1];
    }
    if (rapidApiMatch && rapidApiMatch[1] && !rapidApiMatch[1].includes('你的')) {
      existingRapidApiKey = rapidApiMatch[1];
    }
  }

  const envContent = `# Auto-generated by deployV3.js - ${new Date().toISOString()}
# Network: ${hre.network.name} (Chain ID: ${chainId})

RPC_URL=${getRpcUrl(hre.network.name)}
PRIVATE_KEY=${existingPrivateKey}

PREDICTION_MARKET_ADDRESS=${predictionAddress}
CREATOR_MARKET_ADDRESS=${creatorAddress}
USDC_ADDRESS=${usdcAddress}

RAPIDAPI_KEY=${existingRapidApiKey}
RAPIDAPI_HOST=twitter241.p.rapidapi.com

PORT=3001
`;

  // 同时写 .env 和 .env.example
  try {
    fs.writeFileSync(oracleEnvPath, envContent);
    console.log("✅ Updated oracle-node/.env");
    
    fs.writeFileSync(path.join(oracleDir, ".env.example"), envContent);
    console.log("✅ Updated oracle-node/.env.example");
  } catch (error) {
    console.log("⚠️ Could not update oracle .env:", error.message);
  }

  // 打印总结
  console.log("\n" + "=".repeat(60));
  console.log("🎉 ALL CONTRACTS DEPLOYED SUCCESSFULLY!");
  console.log("=".repeat(60));
  console.log("\n📋 Contract Addresses:");
  console.log("   MockUSDC:            ", usdcAddress);
  console.log("   PredictionMarketV3:  ", predictionAddress);
  console.log("   CreatorMarketV2:     ", creatorAddress);
  console.log("\n🌐 Network Info:");
  console.log("   Network:  ", hre.network.name);
  console.log("   Chain ID: ", chainId);
  console.log("   Deployer: ", deployer.address);
  console.log("=".repeat(60));
}

function getRpcUrl(networkName) {
  const rpcUrls = {
    sepolia: "https://eth-sepolia.g.alchemy.com/v2/BVg93ArKlmUQFHzHqureN",
    baseSepolia: "https://sepolia.base.org",
    base: "https://mainnet.base.org",
    mainnet: "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY",
    localhost: "http://127.0.0.1:8545"
  };
  return rpcUrls[networkName] || "https://sepolia.base.org";
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});