const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with:", deployer.address);
  console.log("Network:", hre.network.name);

  // 1. Deploy MockUSDC
  console.log("\n1. Deploying MockUSDC...");
  const MockUSDC = await hre.ethers.getContractFactory("MockUSDC");
  const usdc = await MockUSDC.deploy();
  await usdc.waitForDeployment();
  const usdcAddress = await usdc.getAddress();
  console.log("   MockUSDC:", usdcAddress);

  // 2. Deploy PredictionMarketV2
  console.log("\n2. Deploying PredictionMarketV2...");
  const PredictionMarket = await hre.ethers.getContractFactory("PredictionMarketV2");
  const predictionMarket = await PredictionMarket.deploy(usdcAddress);
  await predictionMarket.waitForDeployment();
  const predictionAddress = await predictionMarket.getAddress();
  console.log("   PredictionMarketV2:", predictionAddress);

  // 3. Deploy CreatorMarketV2
  console.log("\n3. Deploying CreatorMarketV2...");
  const CreatorMarket = await hre.ethers.getContractFactory("CreatorMarketV2");
  const creatorMarket = await CreatorMarket.deploy(usdcAddress);
  await creatorMarket.waitForDeployment();
  const creatorAddress = await creatorMarket.getAddress();
  console.log("   CreatorMarketV2:", creatorAddress);

  // ============ 获取 Chain ID ============
  const network = await hre.ethers.provider.getNetwork();
  const chainId = Number(network.chainId);

  // ============ 4. 保存 deployed-addresses.json ============
  const addresses = {
    MockUSDC: usdcAddress,
    PredictionMarketV2: predictionAddress,
    CreatorMarketV2: creatorAddress,
    deployer: deployer.address,
    network: hre.network.name,
    chainId: chainId,
    timestamp: new Date().toISOString()
  };

  fs.writeFileSync(
    "deployed-addresses.json",
    JSON.stringify(addresses, null, 2)
  );
  console.log("\n✅ Saved deployed-addresses.json");

  // ============ 5. 自动更新前端 config.ts ============
  const frontendConfigPath = path.join(__dirname, "../../frontend/src/constants/config.ts");
  
  const configContent = `// Auto-generated by deployV2.js - ${new Date().toISOString()}
// Network: ${hre.network.name} (Chain ID: ${chainId})

export const PREDICTION_MARKET_ADDRESS = "${predictionAddress}";
export const CREATOR_MARKET_ADDRESS = "${creatorAddress}";
export const USDC_ADDRESS = "${usdcAddress}";
export const CHAIN_ID = ${chainId};
export const CHAIN_NAME = "${hre.network.name}";

// USDC decimals
export const USDC_DECIMALS = 6;

// RPC URL (for reference)
export const RPC_URL = "${getRpcUrl(hre.network.name)}";
`;

  try {
    fs.writeFileSync(frontendConfigPath, configContent);
    console.log("✅ Updated frontend/src/constants/config.ts");
  } catch (error) {
    console.log("⚠️ Could not update frontend config:", error.message);
    console.log("   Please update manually with the addresses above.");
  }

  // ============ 6. 自动更新 Oracle .env.example ============
  const oracleEnvPath = path.join(__dirname, "../../oracle-node/.env.example");
  
  const envContent = `# Auto-generated by deployV2.js - ${new Date().toISOString()}
# Network: ${hre.network.name} (Chain ID: ${chainId})

# ============ 网络配置 ============
RPC_URL=${getRpcUrl(hre.network.name)}

# ============ 钱包配置 ============
# Oracle 钱包私钥（需要有 ETH 支付 gas）
PRIVATE_KEY=你的私钥

# ============ 合约地址 ============
PREDICTION_MARKET_ADDRESS=${predictionAddress}
CREATOR_MARKET_ADDRESS=${creatorAddress}
USDC_ADDRESS=${usdcAddress}

# ============ Twitter API 配置 ============
RAPIDAPI_KEY=你的RapidAPI密钥
RAPIDAPI_HOST=twitter241.p.rapidapi.com
`;

  try {
    // 确保 oracle-node 目录存在
    const oracleDir = path.join(__dirname, "../../oracle-node");
    if (!fs.existsSync(oracleDir)) {
      fs.mkdirSync(oracleDir, { recursive: true });
    }
    fs.writeFileSync(oracleEnvPath, envContent);
    console.log("✅ Updated oracle-node/.env.example");
  } catch (error) {
    console.log("⚠️ Could not update oracle .env.example:", error.message);
  }

  // ============ 打印总结 ============
  console.log("\n" + "=".repeat(60));
  console.log("🎉 ALL CONTRACTS DEPLOYED SUCCESSFULLY!");
  console.log("=".repeat(60));
  console.log("\n📋 Contract Addresses:");
  console.log("   MockUSDC:           ", usdcAddress);
  console.log("   PredictionMarketV2: ", predictionAddress);
  console.log("   CreatorMarketV2:    ", creatorAddress);
  console.log("\n🌐 Network Info:");
  console.log("   Network:  ", hre.network.name);
  console.log("   Chain ID: ", chainId);
  console.log("   Deployer: ", deployer.address);
  console.log("\n📁 Files Updated:");
  console.log("   ✅ contracts/deployed-addresses.json");
  console.log("   ✅ frontend/src/constants/config.ts");
  console.log("   ✅ oracle-node/.env.example");
  console.log("\n⚠️  NEXT STEPS:");
  console.log("   1. Copy oracle-node/.env.example to oracle-node/.env");
  console.log("   2. Fill in your PRIVATE_KEY and RAPIDAPI_KEY");
  console.log("   3. Push to GitHub to trigger Vercel rebuild");
  console.log("   4. Deploy Oracle to Railway");
  console.log("=".repeat(60));
}

// 根据网络名称返回对应的 RPC URL
function getRpcUrl(networkName) {
  const rpcUrls = {
    sepolia: "https://eth-sepolia.g.alchemy.com/v2/BVg93ArKlmUQFHzHqureN",
    baseSepolia: "https://sepolia.base.org",
    base: "https://mainnet.base.org",
    mainnet: "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY",
    localhost: "http://127.0.0.1:8545"
  };
  return rpcUrls[networkName] || "https://sepolia.base.org";
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});