// Auto-generated by deployV2.js - 2026-01-23T07:48:56.586Z
export const PREDICTION_MARKET_ADDRESS = "0xFb23bBece7AB86Dd836c30ff48D9C203f065AAF4";
export const USDC_ADDRESS = "0x1e713665b39fdebc921c15F1b80cC8C7C15Ab9D3";
export const CHAIN_ID = 11155111;
export const CHAIN_NAME = "sepolia";

// USDC decimals
export const USDC_DECIMALS = 6;
