// Auto-generated by deployV4.js - 2026-01-29T01:22:32.597Z
// Network: sepolia (Chain ID: 11155111)

export const PREDICTION_MARKET_ADDRESS = "0x740FCfe55805fCF291ab873D3d8aC5407e71B4C5";
export const CREATOR_MARKET_ADDRESS = "0xbE245b43C802e9f6B70DB94Efa84c19d7207D724";
export const USDC_ADDRESS = "0x118926B20Df05B694DE5074874fC141d2b3E11ee";
export const CHAIN_ID = 11155111;
export const CHAIN_NAME = "sepolia";

// USDC decimals
export const USDC_DECIMALS = 6;

// Contract versions
export const PREDICTION_MARKET_VERSION = 4;
export const CREATOR_MARKET_VERSION = 3;

// Prediction Market 算法类型
export enum PricingAlgorithm {
  CPMM = 0,   // 恒定乘积做市商
  LMSR = 1    // 对数市场评分规则
}

// Creator Market 曲线类型
export enum CurveType {
  LINEAR = 0,      // 线性曲线: price = A * supply + B
  EXPONENTIAL = 1, // 指数曲线: price = B + A * supply²
  SIGMOID = 2      // S型曲线: 早期慢 -> 中期快 -> 后期慢
}

// 默认曲线参数
export const DEFAULT_CURVE_A = 10000;        // 0.01 USDC 斜率
export const DEFAULT_CURVE_B = 1000000;      // 1 USDC 基础价格
export const DEFAULT_INFLECTION = 100;       // Sigmoid 拐点
export const DEFAULT_LMSR_B = "100000000000000000000"; // 100 * 10^18

// RPC URL (for reference)
export const RPC_URL = "https://eth-sepolia.g.alchemy.com/v2/BVg93ArKlmUQFHzHqureN";
